ja:
  app_title: "Excel転記ツール"
  section_transfer: "Excel転記"
  label_transfer_config: "転記設定CSVファイル"
  button_transfer: "転記実行"
  message_title_success: "成功"
  message_title_error: "エラー"
  message_transfer_success: "転記完了しました"
  error_transfer_no_jobs: "転記対象が存在しません。"
  error_transfer_failed: "転記中にエラーが発生しました"
  error_file_not_found: "設定ファイルが見つかりません。"
  error_restore_success: "エラー発生のためバックアップから復元しました。"
  error_restore_failed: "エラー発生。復元できるバックアップが存在しません。"
  log_startup: "アプリ起動"
  log_shutdown: "アプリ終了"
  log_file_selected: "ファイル選択"
  log_file_select_error: "ファイル選択エラー"
  log_transfer_no_jobs: "転記対象なし"
  log_file_not_found: "ファイル未発見"
