ja:
  app_title: "Excel ユーティリティ（転記 / Grep / Diff / Count）"
  section_transfer: "転記"
  section_grep: "Grep（横断検索）"
  section_diff: "Diff（差分）"
  label_transfer_config: "転記定義CSV"
  button_transfer: "実行"
  label_grep_root: "検索ルートフォルダ"
  label_grep_keyword: "検索キーワード"
  button_grep: "実行"
  label_diff_file_a: "File A"
  label_diff_file_b: "File B"
  label_diff_key_cols: "主キー列（カンマ区切り）"
  button_diff: "実行"
  check_ignore_case: "大文字小文字を無視"
  check_compare_formula: "数式で比較（表示値ではなく）"
