ja:
  app_title: "PPTX 翻訳サポートツール"
  section_export: "① 日本語PPTX -> CSV出力"
  section_import: "② 翻訳済みCSV -> 英語PPTX作成"
  label_input_pptx: "日本語PPTXファイル"
  label_output_csv: "CSV出力先"
  button_export: "エクスポート"
  label_original_pptx: "元の日本語PPTXファイル"
  label_translated_csv: "翻訳済みCSVファイル"
  label_output_pptx: "英語版PPTX保存先"
  button_import: "インポート"
  message_title_success: "完了"
  message_title_error: "エラー"
  message_export_success: "CSVファイルを作成しました"
  message_export_error: "CSV作成中にエラーが発生しました"
  message_import_success: "英語版PPTXファイルを作成しました"
  message_import_error: "英語版PPTX作成中にエラーが発生しました"
  error_config_folder_not_found_title: "エラー"
  error_config_folder_not_found_message: "設定フォルダ(config)が見つかりません。プログラムを終了します。"
  log_config_folder_not_found: "設定フォルダ(config)が存在しないため終了しました"
  log_startup: "アプリケーション起動"
  log_shutdown: "アプリケーション終了"
  log_settings_loaded: "設定ファイルを正常に読み込みました。"
  log_settings_load_error: "設定ファイル読み込みエラー"
  log_csv_export_start: "CSV出力開始"
  log_csv_export_success: "CSV出力成功"
  log_csv_export_failure: "CSV出力失敗"
  log_pptx_create_start: "PPTX作成開始"
  log_pptx_create_success: "PPTX作成成功"
  log_pptx_create_failure: "PPTX作成失敗"
  log_file_selected: "ファイル選択"
  log_file_select_error: "ファイル選択エラー"

en:
  app_title: "PPTX Translation Support Tool"
  section_export: "① Export Japanese PPTX to CSV"
  section_import: "② Create English PPTX from Translated CSV"
  label_input_pptx: "Japanese PPTX File"
  label_output_csv: "CSV Output Destination"
  button_export: "Export"
  label_original_pptx: "Original Japanese PPTX File"
  label_translated_csv: "Translated CSV File"
  label_output_pptx: "English PPTX Save Destination"
  button_import: "Import"
  message_title_success: "Success"
  message_title_error: "Error"
  message_export_success: "CSV file created successfully"
  message_export_error: "Error occurred during CSV creation"
  message_import_success: "English PPTX file created successfully"
  message_import_error: "Error occurred during English PPTX creation"
  error_config_folder_not_found_title: "Error"
  error_config_folder_not_found_message: "The 'config' folder was not found. The program will exit."
  log_config_folder_not_found: "The 'config' folder is missing. Terminating program."
  log_startup: "Application started"
  log_shutdown: "Application closed"
  log_settings_loaded: "Configuration files loaded successfully."
  log_settings_load_error: "Error loading configuration files."
  log_csv_export_start: "Starting CSV export"
  log_csv_export_success: "CSV export completed successfully"
  log_csv_export_failure: "CSV export failed"
  log_pptx_create_start: "Starting PPTX creation"
  log_pptx_create_success: "PPTX creation completed successfully"
  log_pptx_create_failure: "PPTX creation failed"
  log_file_selected: "File selected"
  log_file_select_error: "File selection error"
